### ISSUE TITLE
Dongle-less connection

### ISSUE THREAD

**Issue by rhofour** [qtux/myo-raw#6]
Do you have any sense of how much work it would take to make the Myo work without the dongle? It seems kind of silly to use it when any modern computer should already have a decent bluetooth chip.

Thalmic Labs already open-sourced the BLE protocol at https://github.com/thalmiclabs/myo-bluetooth . There are also some other projects on Github that have it working, but I didn't see one that was actually properly licensed or maintained.

I might give it a try using Bluez, but I suspect this would need to be done separately for each platform.

**Comment by qtux** [comment]
Did you have a look at https://github.com/Alvipe/Open-Myo? I did not try it yet, but it sounds promising to me. I would be interested in merging that with this library to have both means of connecting the devices available and I am open to adapt the current license to GPLv3 to satisfy the license requirement. I think that could be done in a reasonable amount of time.

I will have a look on that as that is something I was planing to do, but feel free to make pull requests. I will review and test them on Linux.

Besides, I think it is fine if this dongle-less approach would only work with Linux, because the other approach would be still available for the other platforms.

**Comment by qtux** [comment]
Dongle-less is working now on Linux. I adapted the previous Bluetooth class to be similar to the bluepy.btle.Peripheral class and added the bluepy implementaiton as an optional backend. Note the Bluetooth configuration issues regarding the bandwidth in the README.
